title: Parker Hong
description: My personal portfolio site
baseurl: ""  # Leave blank for user/organization site
url: "https://parkerhong2005.github.io"

# Tell Jekyll where to look for custom layout
markdown: kramdown
theme: null  # disable default theme completely

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default

collections:
  projects:
    output: true
    permalink: /projects/:name/
